<?php

namespace App\Http\Controllers\ForensicController;

use App\Http\Controllers\Controller;
use App\Models\Complaint;
use App\Models\Media;
use App\Models\PendingSummaries;
use App\Models\Transcription;
use App\Models\TranscriptionVerification;
use App\Models\ForensicReview;
use App\Helpers\NotificationHelper; // Add this
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Http;
use Barryvdh\DomPDF\Facade\Pdf;

class AIController extends Controller
{
    public function detectFaces($id)
    {
        // Your AI Face Detection Logic Here
        // Placeholder:
        
        // ✅ **NEW: Face detection notification**
        NotificationHelper::createForUser(
            Auth::id(),
            "Face Detection Complete",
            "AI face detection completed for case #{$id}",
            'success',
            route('forensic.case.details', $id)
        );
        
        return back()->with('success', 'Face detection completed.');
    }

    public function transcribeAudio($id)
    {
        $case = Complaint::findOrFail($id);

        // Fake transcription for now
        $transcription = "This is a sample transcription generated by AI. The audio evidence contains important information related to the case. Key points include the time of incident, location details, and descriptions of involved parties.";

        // Save to transcriptions table instead of complaints table
        $transcriptionRecord = Transcription::create([
            'complaint_id' => $id,
            'transcript' => $transcription,
            'is_verified' => false,
        ]);

        // ✅ **NEW: Transcription completion notification**
        NotificationHelper::createForUser(
            Auth::id(),
            "Audio Transcription Complete",
            "AI transcription completed for case #{$case->track_id}",
            'success',
            route('forensic.transcript')
        );

        // ✅ **NEW: Notify admin about completed transcription
        $admins = \App\Models\User::where('role_id', 1)->active()->get();
        foreach ($admins as $admin) {
            NotificationHelper::createForUser(
                $admin->id,
                "Forensic Transcription Complete",
                "Forensic analyst completed AI transcription for case #{$case->track_id}",
                'info',
                route('admin.complaints.show', $id)
            );
        }

        return back()->with('success', 'Transcription completed and saved to database.');
    }

    public function generateSummary($id)
    {
        $case = Complaint::findOrFail($id);

        // Get latest transcription
        $latestTranscription = Transcription::where('complaint_id', $id)
            ->orderBy('created_at', 'desc')
            ->first();

        // Check: Case must have transcription
        if (!$latestTranscription || empty($latestTranscription->transcript)) {
            return back()->with('error', 'No transcription found for this complaint. Please transcribe the audio first.');
        }

        // Check: Summary already exists
        $existing = PendingSummaries::where('complaint_id', $id)->first();
        if ($existing) {
            return back()->with('success', 'AI summary already exists and is waiting for approval.');
        }

        // AI Summary Generation
        $prompt = "Summarize the following forensic case transcription professionally and concisely:\n\n" . $latestTranscription->transcript;

        // Temporary fake AI summary
        $aiSummary = "**AI GENERATED SUMMARY**\n\n";
        $aiSummary .= "Based on the audio transcription, the following key points were identified:\n";
        $aiSummary .= "1. Incident occurred at the specified location\n";
        $aiSummary .= "2. Multiple parties were involved in the conversation\n";
        $aiSummary .= "3. Time references suggest the incident happened in the evening\n";
        $aiSummary .= "4. Emotional tones indicate potential conflict situation\n";
        $aiSummary .= "5. Specific details about individuals mentioned\n\n";
        $aiSummary .= "This summary requires forensic analyst verification and approval.";

        // Save to pending_summaries table
        $summary = PendingSummaries::create([
            'summary_text' => $aiSummary,
            'user_id'      => Auth::id(),  // forensic analyst
            'complaint_id' => $id,
            'status'       => 'pending',
            'approved_by'  => null,
        ]);

        // ✅ **NEW: AI summary generation notification**
        NotificationHelper::createForUser(
            Auth::id(),
            "AI Summary Generated",
            "AI summary generated for case #{$case->track_id} and sent for approval",
            'success',
            route('forensic.summary.approved')
        );

        // ✅ **NEW: Notify admin about new AI summary
        $admins = \App\Models\User::where('role_id', 1)->active()->get();
        foreach ($admins as $admin) {
            NotificationHelper::createForUser(
                $admin->id,
                "AI Summary Generated for Review",
                "Forensic analyst generated AI summary for case #{$case->track_id}",
                'info',
                route('admin.summaries.index')
            );
        }

        return back()->with('success', 'AI summary generated from transcription and sent for approval.');
    }

    public function generateAIReport($id)
    {
        $case = Complaint::with([
            'user',
            'media',
            'summaries' => function($query) {
                $query->orderBy('created_at', 'desc');
            },
            'transcriptions' => function($query) {
                $query->with('verifications')
                      ->orderBy('created_at', 'desc');
            },
            'latestForensicReview'
        ])->findOrFail($id);

        // Get latest verified transcription
        $verifiedTranscription = null;
        foreach ($case->transcriptions as $transcription) {
            if ($transcription->verifications && $transcription->verifications->isNotEmpty()) {
                $verification = $transcription->verifications->first();
                if ($verification->approved) {
                    $verifiedTranscription = $verification->corrected_text;
                    break;
                }
            }
        }

        // Get latest approved summary
        $approvedSummary = $case->summaries
            ->where('status', 'approved')
            ->first();

        // ✅ **NEW: AI report generation notification**
        NotificationHelper::createForUser(
            Auth::id(),
            "AI Report Generated",
            "AI forensic report generated for case #{$case->track_id}",
            'success',
            route('forensic.report', $id)
        );

        return view('forensic_analyst.ai-report', compact(
            'case', 
            'verifiedTranscription',
            'approvedSummary'
        ));
    }

    public function exportPDF($id)
    {
        $case = Complaint::with([
            'user',
            'media',
            'summaries' => function($query) {
                $query->where('status', 'approved')
                      ->orderBy('created_at', 'desc');
            },
            'transcriptions' => function($query) {
                $query->with(['verifications' => function($q) {
                    $q->where('approved', 1);
                }])->orderBy('created_at', 'desc');
            },
            'latestForensicReview'
        ])->findOrFail($id);

        // Get latest verified transcription for PDF
        $verifiedTranscription = null;
        foreach ($case->transcriptions as $transcription) {
            if ($transcription->verifications && $transcription->verifications->isNotEmpty()) {
                $verification = $transcription->verifications->first();
                if ($verification->approved) {
                    $verifiedTranscription = $verification->corrected_text;
                    break;
                }
            }
        }

        // ✅ **NEW: PDF export notification**
        NotificationHelper::createForUser(
            Auth::id(),
            "PDF Report Exported",
            "Forensic PDF report exported for case #{$case->track_id}",
            'success',
            route('forensic.case.details', $id)
        );

        // ✅ **NEW: Notify admin about PDF export
        $admins = \App\Models\User::where('role_id', 1)->active()->get();
        foreach ($admins as $admin) {
            NotificationHelper::createForUser(
                $admin->id,
                "Forensic Report Exported",
                "Forensic analyst exported PDF report for case #{$case->track_id}",
                'info',
                route('admin.complaints.show', $id)
            );
        }

        $pdf = Pdf::loadView('forensic_analyst.partials.report-pdf', compact(
            'case', 
            'verifiedTranscription'
        ));
        $pdf->setPaper('A4', 'portrait');

        return $pdf->download('Forensic_Report_Case_'.$case->track_id.'_'.date('Ymd_His').'.pdf');
    }
}