@extends('layouts.master')

@section('title', 'AI Summary Approval')

@section('content')
<div class="container py-4">
<div class="mt-4 p-4">
    <h3 class="fw-bold mb-4">
        <i class="bi bi-robot"></i> AI Summary Approval Panel
    </h3>

    <!-- Filters -->
    <form class="row g-2 mb-4">
        <div class="col-md-3">
            <select name="status" class="form-select" onchange="this.form.submit()">
                <option value="">-- Filter by Status --</option>
                <option value="pending" {{ request('status')=='pending'?'selected':'' }}>Pending</option>
                <option value="approved" {{ request('status')=='approved'?'selected':'' }}>Approved</option>
                <option value="rejected" {{ request('status')=='rejected'?'selected':'' }}>Rejected</option>
            </select>
        </div>
    </form>

    <!-- Summary Table -->
    <div class="card shadow">
        <div class="card-body table-responsive">

            <table class="table table-bordered align-middle text-center">
                <thead class="table-light">
                    <tr>
                        <th>ID</th>
                        <th>Complaint</th>
                        <th>Generated By</th>
                        <th>Status</th>
                        <th>Created</th>
                        <th>Actions</th>
                    </tr>
                </thead>

                <tbody>
                    @forelse ($summaries as $summary)
                    @php
                        $statusClass = [
                            'pending' => 'badge bg-warning text-dark',
                            'approved' => 'badge bg-success',
                            'rejected' => 'badge bg-danger',
                        ][$summary->status];
                    @endphp

                    <tr>
                        <td>{{ $summary->id }}</td>

                        <td>
                            <strong>#{{ $summary->complaint->id }}</strong><br>
                            <small class="text-muted">{{ $summary->complaint->track_id }}</small>
                        </td>

                        <td>{{ $summary->generatedBy->name ?? 'N/A' }}</td>

                        <td>
                            <span class="{{ $statusClass }}">
                                {{ ucfirst($summary->status) }}
                            </span>
                        </td>

                        <td>{{ $summary->created_at->format('d M Y') }}</td>

                        <td>
                            <!-- View Button -->
                            <button class="btn btn-sm btn-primary" data-bs-toggle="modal"
                                data-bs-target="#summaryModal{{ $summary->id }}">
                                <i class="bi bi-eye"></i> View
                            </button>

                            @if($summary->status == 'pending')
                            <!-- Approve -->
                            <form action="{{ route('admin.summaries.approve', $summary->id) }}" method="POST" class="d-inline">
                                @csrf
                                <button class="btn btn-success btn-sm">
                                    <i class="bi bi-check2"></i> Approve
                                </button>
                            </form>

                            <!-- Reject -->
                            <form action="{{ route('admin.summaries.reject', $summary->id) }}" method="POST" class="d-inline">
                                @csrf
                                <button class="btn btn-danger btn-sm">
                                    <i class="bi bi-x"></i> Reject
                                </button>
                            </form>
                            @endif
                        </td>
                    </tr>

                    <!-- Modal -->
                    <div class="modal fade" id="summaryModal{{ $summary->id }}" tabindex="-1">
                        <div class="modal-dialog modal-lg modal-dialog-centered">
                            <div class="modal-content">

                                <div class="modal-header">
                                    <h5 class="modal-title">
                                        Summary #{{ $summary->id }}
                                    </h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                                </div>

                                <div class="modal-body">
                                    <h6 class="fw-bold">Complaint: #{{ $summary->complaint->id }}</h6>
                                    <hr>
                                    <p class="text-secondary" style="white-space:pre-wrap">
                                        {{ $summary->summary_text }}
                                    </p>
                                </div>

                                <div class="modal-footer">
                                    <button class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                </div>

                            </div>
                        </div>
                    </div>

                    @empty
                    <tr>
                        <td colspan="6" class="text-muted py-4">
                            <i class="bi bi-inbox fs-3 d-block mb-2"></i>
                            No summaries found.
                        </td>
                    </tr>
                    @endforelse
                </tbody>
            </table>

            <div class="mt-3">
                {{ $summaries->links() }}
            </div>
        </div>
    </div>
</div>
</div>
@endsection
