@extends('forensic_analyst.layouts.app')
@section('title','AI Report & Case Review')

@section('content')
<div class="container py-4">

  <!-- Header -->
  <div class="d-flex justify-content-between align-items-center mb-4">
    <h3 class="text-primary mb-0">
      <i class="material-icons align-middle">description</i> AI Forensic Report
    </h3>
    <div>
        <a href="{{ route('forensic.case.details', $case->id) }}" class="btn btn-outline-secondary me-2">
          <i class="material-icons align-middle">arrow_back</i> Back to Case
        </a>
        <a href="{{ route('forensic.export.pdf', $case->id) }}" class="btn btn-primary">
          <i class="material-icons align-middle">picture_as_pdf</i> Export PDF
        </a>
    </div>
  </div>

  <!-- Report Card -->
  <div class="card shadow-lg">
    <div class="card-header bg-dark text-white">
      <h5 class="mb-0">
        <i class="material-icons align-middle">folder_open</i> 
        Forensic Analysis Report - Case #{{ $case->track_id ?? $case->id }}
      </h5>
      <small class="text-light">Generated on: {{ now()->format('d M Y, h:i A') }}</small>
    </div>

    <div class="card-body">
      <!-- Case Information Section -->
      <div class="row mb-4">
        <div class="col-md-6">
          <h6 class="text-primary">Case Information</h6>
          <table class="table table-sm table-borderless">
            <tr>
              <th width="40%">Case ID:</th>
              <td>#{{ $case->id }}</td>
            </tr>
            <tr>
              <th>Track ID:</th>
              <td>{{ $case->track_id ?? 'N/A' }}</td>
            </tr>
            <tr>
              <th>Title:</th>
              <td>{{ $case->subject ?? 'N/A' }}</td>
            </tr>
            <tr>
              <th>Filed By:</th>
              <td>{{ $case->user->name ?? 'Unknown' }}</td>
            </tr>
            <tr>
              <th>Incident Type:</th>
              <td>{{ $case->incident_type ?? 'N/A' }}</td>
            </tr>
          </table>
        </div>
        <div class="col-md-6">
          <h6 class="text-primary">Report Details</h6>
          <table class="table table-sm table-borderless">
            <tr>
              <th width="40%">Generated On:</th>
              <td>{{ now()->format('d M Y, H:i') }}</td>
            </tr>
            <tr>
              <th>Generated By:</th>
              <td>{{ Auth::user()->name }}</td>
            </tr>
            <tr>
              <th>Case Status:</th>
              <td>
                <span class="badge bg-{{ $case->status == 'completed' ? 'success' : ($case->status == 'pending' ? 'warning' : 'info') }}">
                  {{ ucfirst($case->status) }}
                </span>
              </td>
            </tr>
            <tr>
              <th>Evidence Count:</th>
              <td>{{ $case->media->count() }} files</td>
            </tr>
          </table>
        </div>
      </div>

      <hr class="my-4">

      <!-- Section 1: Evidence Overview -->
      <h5 class="text-primary mb-3">
        <i class="material-icons align-middle">perm_media</i> Evidence Overview
      </h5>
      @if($case->media->isEmpty())
        <div class="alert alert-info">
          <i class="material-icons align-middle">info</i> No uploaded evidence found.
        </div>
      @else
        <div class="row">
          @foreach($case->media as $evidence)
          <div class="col-md-4 mb-3">
            <div class="card h-100 border-0 shadow-sm">
              <div class="card-body">
                <div class="d-flex align-items-start">
                  @php
                    $ext = strtolower(pathinfo($evidence->file_path, PATHINFO_EXTENSION));
                    $icon = 'insert_drive_file';
                    $color = 'secondary';
                    
                    if(in_array($ext, ['jpg','jpeg','png','gif'])) {
                      $icon = 'image';
                      $color = 'primary';
                    } elseif(in_array($ext, ['mp4','avi','mov'])) {
                      $icon = 'videocam';
                      $color = 'danger';
                    } elseif(in_array($ext, ['mp3','wav','ogg'])) {
                      $icon = 'audiotrack';
                      $color = 'success';
                    }
                  @endphp
                  
                  <i class="material-icons text-{{ $color }} me-3" style="font-size: 36px;">{{ $icon }}</i>
                  <div>
                    <h6 class="mb-1">{{ \Illuminate\Support\Str::limit(basename($evidence->file_path), 30) }}</h6>
                    <p class="text-muted small mb-2">
                      {{ ucfirst($evidence->file_type) }} • 
                      {{ $evidence->created_at->format('d M Y') }}
                    </p>
                    <a href="{{ asset('storage/'.$evidence->file_path) }}" 
                       target="_blank" 
                       class="btn btn-sm btn-outline-primary">
                      <i class="material-icons align-middle" style="font-size: 14px;">visibility</i> View
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
          @endforeach
        </div>
      @endif

      <!-- Section 2: AI Transcription -->
      <h5 class="text-success mt-4 mb-3">
        <i class="material-icons align-middle">mic</i> Audio/Video Transcription
      </h5>
      <div class="card border-success mb-4">
        <div class="card-header bg-success bg-opacity-10 text-success">
          <strong>Transcription Analysis</strong>
          @if($case->transcriptions->count() > 0)
            <span class="badge bg-success float-end">{{ $case->transcriptions->count() }} available</span>
          @endif
        </div>
        <div class="card-body">
       @if(!empty($verifiedTranscription))
            <div class="alert alert-success">
              <i class="material-icons align-middle">verified</i> Verified Transcript
            </div>
            <div class="transcription-content p-3 bg-light rounded">
              <p style="white-space: pre-wrap;">{{ $verifiedTranscription }}</p>
            </div>
          @elseif($case->transcriptions->count() > 0)
            @foreach($case->transcriptions as $transcription)
              <div class="mb-3">
                <div class="d-flex justify-content-between align-items-center mb-2">
                  <small class="text-muted">Transcription #{{ $loop->iteration }}</small>
                  <small class="text-muted">{{ $transcription->created_at->format('M d, Y H:i') }}</small>
                </div>
                <div class="p-3 bg-light rounded">
                  <p style="white-space: pre-wrap;">{{ $transcription->transcript }}</p>
                </div>
              </div>
            @endforeach
          @else
            <div class="alert alert-warning">
              <i class="material-icons align-middle">warning</i> No transcription available yet.
            </div>
          @endif
        </div>
      </div>

      <!-- Section 3: AI Summary -->
      <h5 class="text-info mt-4 mb-3">
        <i class="material-icons align-middle">summarize</i> AI Generated Summary
      </h5>
      <div class="card border-info mb-4">
        <div class="card-header bg-info bg-opacity-10 text-info">
          <strong>Case Summary</strong>
          @if(!empty($approvedSummary))
            <span class="badge bg-success float-end">Approved</span>
          @endif
        </div>
        <div class="card-body">
          @if(!empty($approvedSummary))
            <div class="alert alert-success">
              <i class="material-icons align-middle">check_circle</i> Approved Summary
            </div>
            <div class="summary-content p-3 bg-light rounded">
              <p style="white-space: pre-wrap;">{{ !empty($approvedSummary) ? $approvedSummary->summary_text : '' }}</p>
              <div class="mt-3 d-flex justify-content-between align-items-center">
                <small class="text-muted">
                  <i class="material-icons align-middle" style="font-size: 14px;">person</i>
                  Generated by: {{ !empty($approvedSummary) ? $approvedSummary->user->name ?? 'AI System' : 'AI System' }}
                </small>
                <small class="text-muted">
                  <i class="material-icons align-middle" style="font-size: 14px;">schedule</i>
                  {{ !empty($approvedSummary) ? $approvedSummary->updated_at->format('M d, Y H:i') : '' }}
                </small>
              </div>
            </div>
          @elseif($case->summaries->count() > 0)
            @foreach($case->summaries as $summary)
              <div class="mb-3">
                <div class="d-flex justify-content-between align-items-center mb-2">
                  <div>
                    <small class="text-muted">Summary #{{ $loop->iteration }}</small>
                    <span class="badge bg-{{ $summary->status == 'approved' ? 'success' : ($summary->status == 'rejected' ? 'danger' : 'warning') }} ms-2">
                      {{ ucfirst($summary->status) }}
                    </span>
                  </div>
                  <small class="text-muted">{{ $summary->created_at->format('M d, Y H:i') }}</small>
                </div>
                <div class="p-3 bg-light rounded">
                  <p style="white-space: pre-wrap;">{{ $summary->summary_text }}</p>
                </div>
              </div>
            @endforeach
          @else
            <div class="alert alert-warning">
              <i class="material-icons align-middle">warning</i> No AI summary generated yet.
            </div>
          @endif
        </div>
      </div>

      <!-- Section 4: Face Detection -->
      <h5 class="text-warning mt-4 mb-3">
        <i class="material-icons align-middle">face</i> Face Detection Results
      </h5>
      <div class="card border-warning mb-4">
        <div class="card-header bg-warning bg-opacity-10 text-warning">
          <strong>Biometric Analysis</strong>
        </div>
        <div class="card-body">
          @if(isset($case->face_matches) && count($case->face_matches))
            <div class="alert alert-success">
              <i class="material-icons align-middle">check_circle</i> Face matches detected
            </div>
            <div class="table-responsive">
              <table class="table table-sm">
                <thead>
                  <tr>
                    <th>Match ID</th>
                    <th>Name</th>
                    <th>Confidence</th>
                    <th>Status</th>
                  </tr>
                </thead>
                <tbody>
                  @foreach($case->face_matches as $match)
                    <tr>
                      <td>{{ $match['id'] ?? 'N/A' }}</td>
                      <td><strong>{{ $match['name'] ?? 'Unknown' }}</strong></td>
                      <td>
                        <div class="progress" style="height: 20px;">
                          <div class="progress-bar bg-{{ $match['confidence'] > 80 ? 'success' : ($match['confidence'] > 60 ? 'warning' : 'danger') }}" 
                               role="progressbar" 
                               style="width: {{ $match['confidence'] }}%">
                            {{ $match['confidence'] }}%
                          </div>
                        </div>
                      </td>
                      <td>
                        <span class="badge bg-{{ $match['status'] == 'verified' ? 'success' : 'warning' }}">
                          {{ ucfirst($match['status'] ?? 'pending') }}
                        </span>
                      </td>
                    </tr>
                  @endforeach
                </tbody>
              </table>
            </div>
          @else
            <div class="alert alert-info">
              <i class="material-icons align-middle">info</i> 
              No face matches detected or face detection not yet performed.
            </div>
          @endif
        </div>
      </div>

      <!-- Section 5: Analyst Review -->
      <h5 class="text-danger mt-4 mb-3">
        <i class="material-icons align-middle">rate_review</i> Forensic Analyst Review
      </h5>
      <div class="card border-danger mb-4">
        <div class="card-header bg-danger bg-opacity-10 text-danger">
          <strong>Professional Analysis</strong>
        </div>
        <div class="card-body">
          @if($case->latestForensicReview)
            <div class="analysis-content p-3 bg-light rounded">
              <p style="white-space: pre-wrap;">{{ $case->latestForensicReview->findings }}</p>
              <div class="mt-3 d-flex justify-content-between align-items-center">
                <small class="text-muted">
                  <i class="material-icons align-middle" style="font-size: 14px;">person</i>
                  Analyst: {{ $case->latestForensicReview->analyst->name ?? 'Forensic Analyst' }}
                </small>
                <div>
                  <small class="text-muted me-3">
                    <i class="material-icons align-middle" style="font-size: 14px;">schedule</i>
                    {{ $case->latestForensicReview->created_at->format('M d, Y H:i') }}
                  </small>
                  <span class="badge bg-{{ $case->latestForensicReview->status == 'approved' ? 'success' : ($case->latestForensicReview->status == 'rejected' ? 'danger' : 'warning') }}">
                    {{ ucfirst($case->latestForensicReview->status) }}
                  </span>
                </div>
              </div>
            </div>
          @else
            <div class="alert alert-warning">
              <i class="material-icons align-middle">warning</i> 
              No forensic analysis has been submitted yet.
            </div>
          @endif
        </div>
      </div>

      <!-- Section 6: Final Verdict -->
      <h5 class="text-secondary mt-4 mb-3">
        <i class="material-icons align-middle">flag</i> Final Assessment
      </h5>
      <div class="card border-secondary">
        <div class="card-header bg-secondary bg-opacity-10 text-secondary">
          <strong>Case Conclusion</strong>
        </div>
        <div class="card-body">
          <div class="row">
            <div class="col-md-6">
              <h6>Case Status Summary</h6>
              <ul class="list-unstyled">
                <li class="mb-2">
                  <i class="material-icons align-middle text-{{ $case->media->count() > 0 ? 'success' : 'warning' }}">check_circle</i>
                  Evidence: {{ $case->media->count() }} file(s)
                </li>
                <li class="mb-2">
                  <i class="material-icons align-middle text-{{ $case->transcriptions->count() > 0 ? 'success' : 'warning' }}">check_circle</i>
                  Transcription: {{ $case->transcriptions->count() }} available
                </li>
                <li class="mb-2">
                  <i class="material-icons align-middle text-{{!empty($approvedSummary) ? 'success' : 'warning' }}">check_circle</i>
                  AI Summary: {{ !empty($approvedSummary) ? 'Approved' : 'Pending' }}
                </li>
                <li class="mb-2">
                  <i class="material-icons align-middle text-{{ $case->latestForensicReview ? 'success' : 'warning' }}">check_circle</i>
                  Analyst Review: {{ $case->latestForensicReview ? 'Completed' : 'Pending' }}
                </li>
              </ul>
            </div>
            <div class="col-md-6">
              <h6>Overall Assessment</h6>
              <div class="p-3 bg-light rounded">
                <p class="mb-2"><strong>Case Complexity:</strong> Moderate</p>
                <p class="mb-2"><strong>Evidence Quality:</strong> {{ $case->media->count() > 0 ? 'Available' : 'Required' }}</p>
                <p class="mb-2"><strong>Analysis Status:</strong> {{ ucfirst($case->status) }}</p>
                <p class="mb-0"><strong>Recommendation:</strong> {{ $case->latestForensicReview ? 'Case ready for finalization' : 'Pending analyst review' }}</p>
              </div>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>

</div>

<style>
.transcription-content, .summary-content, .analysis-content {
    max-height: 300px;
    overflow-y: auto;
    border-left: 4px solid #198754;
    padding-left: 15px;
}

.card {
    border-radius: 10px;
}

.card-header {
    border-radius: 10px 10px 0 0 !important;
}

.progress {
    border-radius: 10px;
}
</style>

@endsection